run-dist:
	./build/install/app/bin/app
clean:
	gradle clean
install:
	gradle installDist
reinstall:
	gradle clean
	gradle installDist
run:
	./build/install/app/bin/app -h
lint:
	./gradlew checkstyleMain
test:
	./gradlew test


