name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Build
        run: cd app && make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: "514b107c537155b86b5137a9e2ef5b3beb2a9aebf9f2338c3833129d2c8a5cda"
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
          coverageCommand: cd app && make report
          debug: true
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco